asm(
    ".set noat               \n\t"
    "li    $1,     0x12340000\n\t"
    "ori   $1, $1, 0x5678    \n\t"
    "li    $2,     0x0123    \n\t"
    "ori   $2, $2, 0x4567    \n\t"
    "mul   $3, $1, $2        \n\t"
    "mthi  $1                \n\t"
    "mtlo  $1                \n\t" 
    "mult  $1, $2            \n\t"
    "mfhi  $4                \n\t"
    "mflo  $5                \n\t"
    "madd  $1, $2            \n\t"
    "mfhi  $6                \n\t"
    "mflo  $7                \n\t"
    "msub  $2, $2            \n\t"
    "mfhi  $8                \n\t"
    "mflo  $9                \n\t"
    "maddu $2, $2            \n\t"
    "mfhi  $10               \n\t"
    "mflo  $11               \n\t"
    "msubu $2, $2            \n\t"
    "mfhi  $12               \n\t"
    "mflo  $13               \n\t"
    "multu $1, $2            \n\t"
    "mfhi  $14               \n\t"
    "mflo  $15               \n\t"
    "mthi  $1                \n\t"
    "mtlo  $2                \n\t"
    "mfhi  $16               \n\t"
    "mflo  $17               \n\t"
);
