#!/bin/tcsh

#------------------------------------------------------------------------------
# File              : RUN_SYN
# Description       : Tcsh script to run a simple synthesis of the design
# Primary Author    : Dominic Murphy
# Other Contributors:
#------------------------------------------------------------------------------

set host=`hostname`
set hind="hind.ecs.soton.ac.uk"
set hart="hart.ecs.soton.ac.uk"

if ($host != $hind && $host != $hart) then
    echo "Error: Synthesis requires hind or hart CAD server for tools. Exiting..."
    exit
endif

if ($1 == clean) then
    rm -rf ./work >&/dev/null
    rm ./*.log >&/dev/null
    echo "Cleaned!"
    exit
endif

mkdir -p logs_${2}${1}
mkdir -p work_${2}${1}
cd work_${2}${1} >&/dev/null
source ../DC_Setup.sh

if($1 == check) then
    dc_shell -f "../syn_check.tcl" > ../logs_${2}${1}/check_syn.log
    echo "Complete. Results written to logs_${2}${1}/check_syn.log"
    exit
endif

if($3 == scan)then
    set SCAN = 1
else
    set SCAN = 0
endif

dc_shell -x "set TYPE $1; set CLK_PERIOD $2; set SCAN $SCAN;" -f "../syn_script.tcl" > ../logs_${2}${1}/syn.log
echo "SYN Complete. Results written to logs_${2}${1}/syn.log"
exit

echo "Error: No/Unrecognised argument provided."
exit 1
