#!/bin/tcsh

#------------------------------------------------------------------------------
# File              : RUN_PNR
# Description       : Tcsh script to run a Place & Route
# Primary Author    : Dominic Murphy
# Other Contributors:
#------------------------------------------------------------------------------

set host=`hostname`
set hind="hind.ecs.soton.ac.uk"
set hart="hart.ecs.soton.ac.uk"

if ($host != $hind && $host != $hart) then
    echo "Error: Synthesis requires hind or hart CAD server for tools. Exiting..."
    exit
endif

if ($1 == clean) then
    rm -rf ./work >&/dev/null
    rm ./*.log >&/dev/null
    rm ./encounter* >&/dev/null
    echo "Cleaned!"
    exit
endif

source SOC_Setup.sh

mkdir -p logs_${2}${1}
mkdir -p work_${2}${1}
cd work_${2}${1} >&/dev/null

velocity -wait 60 -init ../pnr_script.tcl > ../logs_${2}${1}/pnr.log
echo "PNR Complete. Results written to logs_${2}${1}/pnr.log"

exit
